
const comments = [
    {
        commentator: 'Ingjerd Hagen',
        comment: 'Vi fikk slipt og behandlet kjøkken og entre gulv. De brukte tre dager, og gjorde en glimrende jobb og nesten ikke støv. Kommunikasjonen var enkel, hyggelig og bra. De var punktlig og ferdig på tid. Prisen var god. Vi kan trygt anbefale dem. Vi er super fornøyd.',
        link: 'https://g.co/kgs/E9eTG7',
        rate: 5,
        features: ['Kvalitet', 'Profesjonalisme', 'Punktlighet', 'Verdi'],
        pictures: ['https://lh3.googleusercontent.com/p/AF1QipPpH7PSWEr2GpTTlEgIvXOoekCz3SCuYHi2fV9X=s125-p-k'],
    },
    {
        commentator: 'Tor Sandal',
        comment: 'Er svært godt fornøyd med utført gulvsliping og lakking. Kan neppe utføres bedre. God kommunikasjon underveis. Gunstig pris. Anbefaler firmaet på det sterkeste.',
        link: 'https://g.co/kgs/8LyNk3',
        rate: 5,
        features: ['Kvalitet', 'Profesjonalisme', 'Punktlighet', 'Responsivitet', 'Verdi'],
        pictures: [],
    },
    {
        commentator: 'Nina Lykke',
        comment: 'Dyktige og erfarne gulvslipere. Etter slipingen viste de oss hvordan gulvet kom til å se ut med ulike farger og lakk vs. olje. Resultatet ble nydelig. Kan varmt anbefale dette firmaet.',
        link: 'https://g.co/kgs/qvKJoC',
        rate: 5,
        features: ['Kvalitet', 'Profesjonalisme', 'Punktlighet', 'Responsivitet', 'Verdi'],
        pictures: ['https://lh3.googleusercontent.com/p/AF1QipNFS1c2GNGrPrDgRaraQR_W8wts_xMKwy_G8YRX=s125-p-k'],
    },
    {
        commentator: 'Jan Peter Aursnes',
        comment: 'Veldig fornøyd med utført arbeid. Slipt stue og kjøkkengulv, samt lakkert. Også slipt utetrapp og terrasse. Kommer til avtalt tid, ferdig når de sier de skal være ferdig. Lette å kommunisere med, hyggelige og flinke folk. Anbefales.',
        link: 'https://g.co/kgs/Dv478A',
        rate: 5,
        features: ['Kvalitet', 'Profesjonalisme', 'Punktlighet', 'Responsivitet', 'Verdi'],
        pictures: [],
    },
    {
        commentator: 'Bjørn Myrås Johannessen',
        comment: 'Perfekt utført jobb med flott resultat. Lite støv, raske og effektive. Kan anbefales!',
        link: 'https://g.co/kgs/P1u32d',
        rate: 5,
        features: [],
        pictures: [],
    },
    {
        commentator: 'Inger Lücht',
        comment: 'Proff og hyggelig service, de kom og slipte og vokset to slitne kjøkkenbenker. Meget god kommunikasjon, punktlig, meget bra utført jobb. Grei pris. Anbefales!!',
        link: 'https://g.co/kgs/3WXg44',
        rate: 5,
        features: ['Kvalitet', 'Profesjonalisme', 'Punktlighet','Responsivitet'],
        pictures: [],
    },
    {
        commentator: 'Sara Fjeldstad',
        comment: 'Veldig fornøyd både med utført gulvsliping, pris og kommunikasjonen før og underveis. De utførte sliping av gulvet mitt som var dekket med både lim- og laminatrester og gulvet ble kjempefint! Anbefales!',
        link: 'https://g.co/kgs/5caHCE',
        rate: 5,
        features: [],
        pictures: [],
    },
    {
        commentator: 'Anna og Armani',
        comment: 'Vi er superfornøyde med våre orginale furugulv som ble slepet ned og lakkert i tobacco av Kamil. Vi har hatt god kommunikasjon hele veien, og han har gjort en helt nydelig jobb! Kan anbefale alle som vil ha flotte gulv.',
        link: 'https://g.co/kgs/AQdjqz',
        rate: 5,
        features: [],
        pictures: [],
    },
    {
        commentator: 'Caroline Stormorken',
        comment: 'Veldig fornøyd med resultatet! Profesjonell aktør med overkommelige priser. Ville anbefalt.',
        link: 'https://g.co/kgs/vcife5',
        rate: 5,
        features: ['Kvalitet', 'Responsivitet'],
        pictures: [],
    },
    {
        commentator: 'Merete og Kenth',
        comment: 'Meget pent arbeid på 36 kvm ink terskler. Ryddig å fint,hyggelige folk og raskt arbeid.',
        link: 'https://g.co/kgs/nfiqTU',
        rate: 5,
        features: ['Profesjonalisme', 'Punktlighet', 'Verdi'],
        pictures: [],
    },
];

export {comments};